env:
  REGISTRY_HOSTNAME: miiu96

name: Build Docker images & push

on:
  push
#on:
#  release:
#    types: [published]

jobs:
  build-docker-images:
    strategy:
      matrix:
        runs-on: [ubuntu-latest]
    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: "Check out code"
        uses: actions/checkout@v2

      - name: "Import environment variables from a file"
        shell: bash
        run: |
          ENV_FILE="${GITHUB_WORKSPACE}/mainnet/.env"
          while read -r line; do
            if [[ "$line" != NODE_TAG* ]] && [[ "$line" != PROXY_TAG* ]] ; then
              continue
            fi
            echo "$line" >> $GITHUB_ENV
          done < ${ENV_FILE}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: miiu96
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push node image
        uses: docker/build-push-action@v2
        with:
          context: ./mainnet
          file: ./elrond-node-obs
          push: true
          tags: ${{ env.REGISTRY_HOSTNAME }}/${{ env.NODE_TAG }}

      - name: Build and push proxy image
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.GITHUB_WORKSPACE }}/mainnet
          file: ./elrond-proxy
          push: true
          tags: ${{ env.REGISTRY_HOSTNAME }}/${{ env.PROXY_TAG }}

